glance_db_user: "glance"
glance_keystone_user: "glance"
glance_keystone_password: "YourSecurePasswordHERE"
glance_db_password: "YourSecurePasswordHERE"
glance_db_address: "172.16.1.2"
memcached_ip: 172.16.1.2
