---
- hosts: all
  become: yes
  remote_user: root 
  become_user: root
  roles:
   - mysql
   - keystone
   - glance
   - memcached
   - dashboard
   - neutron
   - rabbitmq
   - nova
   - kvm
   - placement
