- name: ----- install pre-requisite  -----
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - mariadb-server
    - wget
    - curl
    - git
    - python3-pymysql
  tags: [ mysql ]
  when: mysql == "enabled"


- name: Allow MySQL to listen on all interfaces
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address            = 0.0.0.0'
    state: present
  notify: mysql_restart
  when: 
    - mysql == "enabled"
  tags: [ mysql ]

- name: Check if MySQL is listening on 0.0.0.0:3306
  ansible.builtin.shell: ss -tunlp | grep -i "0.0.0.0:3306"
  register: mysql_check
  ignore_errors: true
  changed_when: false
  tags: [ mysql ]

- name: Print message if MySQL is running
  ansible.builtin.debug:
    msg: "MySQL is successfully listening on 0.0.0.0:3306"
  when: mysql_check.rc == 0
  tags: [ mysql ]

- name:  -----configure root password-----
  community.mysql.mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: yes
    state: present
  become: yes
  when: 
    - mysql == "enabled"
    - mysql_check.rc == 0
  ignore_errors: yes  # <--- Playbook will continue even if this fails
  tags: [ mysql ]



- name: Create OpenStack Databases
  community.mysql.mysql_db:
    name: "{{ item.db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  loop: "{{ openstack_services }}"
  when: 
    - mysql == "enabled"
    - mysql_check.rc == 0
  tags: [ mysql ]
    


- name: Create user with full access to the database
  community.mysql.mysql_user:
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
    priv: "{{ item.db }}.*:ALL"
    host: "%"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  loop: "{{ openstack_services }}"
  when: 
    - mysql == "enabled"
    - mysql_check.rc == 0
  tags: [ mysql ]