- name: ----- install pre-requisite  -----
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - mariadb-server
    - wget
    - curl
    - git
    - python3-pymysql
  tags: [ installation ]
  when: mysql == "enabled"

- name:  -----configure root password-----
  community.mysql.mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: yes
    state: present
  become: yes
  when: mysql == "enabled"
  ignore_errors: yes  # <--- Playbook will continue even if this fails

- name: Create the database
  community.mysql.mysql_db:
    name: "{{ keystone_db_name }}"
    state: present
#    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password: "{{ mysql_root_password }}" # Use the one you set in Step 2
  when: mysql == "enabled"


- name: Create user with full access to the database
  community.mysql.mysql_user:
    name: "{{ keystone_db_user }}"
    password: "{{ keystone_db_password }}"
    priv: "{{ keystone_db_name }}.*:ALL"
    host: "%"  # Allows connection from any host. Use 'localhost' for local only.
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}" # Use the one you set in Step 2
  when: mysql == "enabled"