keystone_db_user: "keystone"
keystone_db_name: "keystone"
keystone_db_password: "YourSecurePasswordHERE"
keystone_db_address: "172.16.1.2"
keystone_admin_password: "YourSecurePasswordHERE"
controller_admin_address: "172.16.1.2"
controller_internal_address: "172.16.1.2"
controller_public_address: "172.16.1.2"
controller_os_auth_url: "http://172.16.1.2:5000/v3"
controller_os_project_name: "admin"
controller_os_username: "admin"
controller_os_password: "YourSecurePasswordHERE"
controller_os_user_domain_name: "openstack"
cinder_db_user: "cinder"
cinder_db_name: "cinder"
cinder_db_password: "YourSecurePasswordHERE"
cinder_db_address: "172.16.1.2"
cinder_admin_password: "YourSecurePasswordHERE"
glance_db_user: "glance"
glance_db_name: "glance"
glance_db_password: "YourSecurePasswordHERE"
glance_db_address: "172.16.1.2"
glance_admin_password: "YourSecurePasswordHERE"
neutron_db_user: "neutron"
neutron_db_name: "neutron"
neutron_db_password: "YourSecurePasswordHERE"
neutron_db_address: "172.16.1.2"
neutron_admin_password: "YourSecurePasswordHERE"
nova_db_user: "nova"
nova_db_name: "nova"
nova_db_password: "YourSecurePasswordHERE"
nova_db_address: "172.16.1.2"
nova_admin_password: "YourSecurePasswordHERE"